### ISSUE TITLE
Add control panel (Mac)

### ISSUE THREAD

**Issue by tgifriday** [studiokrause/obs-lower-thirds#1]
Mac version doesn't seem to have this option:
"Add control panel: View/Panels/Browser panels."

**Comment by hal0x2328** [comment]
The Linux version is also missing this option.

**Comment by DanielRios549** [comment]
Both Linux and macOS version haven't the custom browser docks feature, because of that it is impossible to add the control panel.

**Comment by jnnkB** [comment]
A simple workaround is to add the control panel as a browser source and then hide it. Now you can use the interact feature to control the panel.
